INSERT INTO Department VALUES ("College of Computing");
INSERT INTO Department VALUES ("College of Design");
INSERT INTO Department VALUES ("College of Engineering");
INSERT INTO Department VALUES ("College of Sciences");
INSERT INTO Department VALUES ("Ivan Allen College of Liberal Arts");
INSERT INTO Department VALUES ("Scheller College of Business");
INSERT INTO Major VALUES ("Business Administration","Scheller College of Business");
INSERT INTO Major VALUES ("Computational Media","College of Computing");
INSERT INTO Major VALUES ("Computer Science","College of Computing");
INSERT INTO Major VALUES ("Architecture","College of Design");
INSERT INTO Major VALUES ("Industrial Design","College of Design");
INSERT INTO Major VALUES ("Music Technology","College of Design");
INSERT INTO Major VALUES ("Aerospace Engineering","College of Engineering");
INSERT INTO Major VALUES ("Biomedical Engineering","College of Engineering");
INSERT INTO Major VALUES ("Chemical and Biomolecular Engineering","College of Engineering");
INSERT INTO Major VALUES ("Civil Engineering","College of Engineering");
INSERT INTO Major VALUES ("Computer Engineering","College of Engineering");
INSERT INTO Major VALUES ("Electrical Engineering","College of Engineering");
INSERT INTO Major VALUES ("Environmental Engineering","College of Engineering");
INSERT INTO Major VALUES ("Industrial Engineering","College of Engineering");
INSERT INTO Major VALUES ("Material Science and Engineering","College of Engineering");
INSERT INTO Major VALUES ("Mechanical Engineering","College of Engineering");
INSERT INTO Major VALUES ("Nuclear and Radiological Engineering","College of Engineering");
INSERT INTO Major VALUES ("Applied Mathematics","College of Sciences");
INSERT INTO Major VALUES ("Applied Physics","College of Sciences");
INSERT INTO Major VALUES ("Biochemistry","College of Sciences");
INSERT INTO Major VALUES ("Biology","College of Sciences");
INSERT INTO Major VALUES ("Chemistry","College of Sciences");
INSERT INTO Major VALUES ("Discrete Mathematics","College of Sciences");
INSERT INTO Major VALUES ("Earth and Atmospheric Sciences","College of Sciences");
INSERT INTO Major VALUES ("Physics","College of Sciences");
INSERT INTO Major VALUES ("Psychology","College of Sciences");
INSERT INTO Major VALUES ("Applied Language and Intercultural Studies","Ivan Allen College of Liberal Arts");
INSERT INTO Major VALUES ("Economics","Ivan Allen College of Liberal Arts");
INSERT INTO Major VALUES ("Economics and International Affairs","Ivan Allen College of Liberal Arts");
INSERT INTO Major VALUES ("Global Economics and Modern Languages","Ivan Allen College of Liberal Arts");
INSERT INTO Major VALUES ("HTS","Ivan Allen College of Liberal Arts");
INSERT INTO Major VALUES ("International Affairs","Ivan Allen College of Liberal Arts");
INSERT INTO Major VALUES ("International Affairs and Modern Languages","Ivan Allen College of Liberal Arts");
INSERT INTO Major VALUES ("LMC","Ivan Allen College of Liberal Arts");
INSERT INTO Major VALUES ("Public Policy","Ivan Allen College of Liberal Arts");