INSERT INTO Application VALUES ('student6','Epic Intentions',CURDATE(),'pending');
INSERT INTO Application VALUES ('slandry8','Epic Intentions',CURDATE(),'pending');
INSERT INTO Application VALUES ('student7','Epic Intentions',CURDATE(),'pending');
INSERT INTO Application VALUES ('student17','Epic Intentions',CURDATE(),'pending');
INSERT INTO Application VALUES ('student14','Epic Intentions',CURDATE(),'pending');
INSERT INTO Application VALUES ('student10','Epic Intentions',CURDATE(),'pending');
INSERT INTO Application VALUES('slandry8','Projek1',CURDATE(),'pending');
INSERT INTO Application VALUES ('student4','Projek1',CURDATE(),'pending');
INSERT INTO Application VALUES ('student17','Excel Current Events',CURDATE(),'pending');
INSERT INTO Application VALUES ('student14','Projek2',CURDATE(),'pending');
INSERT INTO Application VALUES ('student9','ESW Hydroponics/Urban Farming Project',CURDATE(),'pending');
INSERT INTO Application VALUES ('student5','ESW Hydroponics/Urban Farming Project',CURDATE(),'pending');
INSERT INTO Application VALUES ('student14','Projek6',CURDATE(),'pending');
INSERT INTO Application VALUES ('student14','Projek7',CURDATE(),'pending');
INSERT INTO Application VALUES ('student2','Shakespeare in Prison Project',CURDATE(),'pending');
INSERT INTO Application VALUES ('student2','Projek8',CURDATE(),'pending');
INSERT INTO Application VALUES ('student10','Projek10',CURDATE(),'pending');
INSERT INTO Application VALUES ('student12','Projek11',CURDATE(),'pending');
INSERT INTO Application VALUES ('slandry8','Projek8',CURDATE(),'pending');